apiVersion: v1
kind: Secret
metadata:
  name: make-your-secret
  labels:
    {{- include "make-your-time.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.user | b64enc | quote }}
  pass: {{ .Values.pass | b64enc | quote }}
