apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "make-your-time.fullname" . }}
  labels:
    {{- include "make-your-time.labels" . | nindent 4 }}
spec:
  podManagementPolicy: "Parallel"
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "make-your-time.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "make-your-time.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "make-your-time.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: mogusconf
              mountPath: /app/mogusconf.yaml
              subPath: mogusconf.yaml
            - name: ohh-yeah
              mountPath: /app/ohh_yeah/
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          env:
            - name: HELM_USER
              valueFrom:
                secretKeyRef:
                  name: make-your-secret
                  key: user
            - name: HELM_PASS
              valueFrom:
                secretKeyRef:
                  name: make-your-secret
                  key: pass
          ports:
            - name: http
              containerPort: {{ .Values.service.container_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.container_port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.container_port }}
            initialDelaySeconds: 10
            periodSeconds: 10
      initContainers:
        - name: ohh-yeah
          image: busybox:1.28
          command:
            - wget
            - "-O"
            - "/app/ohh_yeah/ohh_yeah.png"
            - "https://steamcommunity-a.akamaihd.net/economy/emoticon/:ohh_yeah:"
          volumeMounts:
            - name: ohh-yeah
              mountPath: "/app/ohh_yeah/"
      volumes:
        - name: mogusconf
          configMap:
            name: make-your-time-configpain
        - name: ohh-yeah
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
