repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --line-length=88
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: bash ./run_tests.sh
        language: python
        stages: [commit]
