---
- name: U p d a t i n g . . .
  tags:
    - os
  run_once: true
  hosts: yandex_vms
  roles:
    - system_update

- name: Deploy Docker
  tags:
    - docker
  hosts: yandex_vms
  roles:
    - app_python
