---
- name: U p d a t i n g . . .
  tags:
    - os
  hosts: yandex_vms
  roles:
    - system_update

- name: Install Docker
  tags:
    - setup
    - docker
  hosts: yandex_vms
  become: true
  roles:
    - docker

- name: Deploy Docker
  tags:
    - docker
  hosts: yandex_vms
  roles:
    - app_python
