---
- name: D E S T R O Y old versions of Docker
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: true

- name: Update requirements
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest

- name: Add GPG key for Docker repo
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present
  become: true

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - containerd.io

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
  become: true
