---
- name: D E S T R O Y old versions of Docker
  tags:
    - setup
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: true

- name: Update requirements
  tags:
    - setup
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest

- name: Add GPG key for Docker repo
  tags:
    - setup
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present
  become: true

- name: Add Docker APT repository
  tags:
    - setup
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker
  tags:
    - setup
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - containerd.io

- name: Install Docker Module for Python
  tags:
    - setup
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose

- name: Install docker-compose
  tags:
    - setup
  remote_user: ubuntu
  get_url:
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Start Docker service
  tags:
    - docker
  service:
    name: docker
    state: started
    enabled: true
  become: true
