positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: monging_global_docker_logs_please_help_me_i_just_want_to_survive
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            time: time
            container_name: attrs.tag
      - labels:
          container_name:
      - match:
          selector: '{job="docker",container_name=""}'
          action: drop
