name: Test, Build, Push, Gregify

on: [push, pull_request]

jobs:
  run_app_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install Requirements
        run: |
          sudo apt-get update -y && sudo apt-get install make
          pip install --no-cache-dir --upgrade pip setuptools wheel
          pip install --no-cache-dir -r requirements-dev.txt
      - name: Run Linter
        run: make run_linter
      - name: Run Tests
        run: make run_tests_main

  docker_build:
    needs: run_app_tests
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/make_your_time:test_build
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/make_your_time:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/make_your_time:buildcache,mode=max

  docker_push:
    needs: run_app_tests
    if: >-
      ${{
        github.event_name == 'push' &&
        (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
      }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/make_your_time:latest
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/make_your_time:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/make_your_time:buildcache,mode=max
